### ISSUE TITLE
snitc not breaking when wrong type of dataset is supplied

### ISSUE THREAD

**Issue by lucas-johnson** [brazil-data-cube/stmetrics#13]
Looks like an awesome package that is going to be super helpful! I'm just getting started here. Thanks for building this!

### Behavior
When I accidentally passed a `<class 'numpy.ndarray'>` instead of a `<class 'rasterio.io.DatasetReader'>` as the dataset argument to `stmetrics.spatial.snitc()` I get the following error:

```
Traceback (most recent call last):
  File "/Users/lucasj/Code/lib/stseg/test.py", line 14, in <module>
    segments = stmetrics.spatial.snitc(
  File "/Users/lucasj/Code/lib/stseg/venv/lib/python3.9/site-packages/stmetrics/spatial.py", line 100, in snitc
    for band in range(img.shape[0]):
UnboundLocalError: local variable 'img' referenced before assignment
```

### Expected behavior
The program should break on this `TypeError`: 
https://github.com/brazil-data-cube/stmetrics/blob/dd988d406fa090738a4d50461e9a46492d2f078e/stmetrics/spatial.py#L96

### Suggestion
Consider using `Raise` to stop the execution like:
```
else:
    raise TypeError("Sorry we can't read this type of file. \
                     Please use Rasterio or xarray")
```

**Comment by andersonreisoares** [comment]
Thank you for bring this to our attention @lucas-johnson. 

This will be fixed in our next commit. I'm also adding a test function to make sure this is working.
